package com.unicauca.demoobserver.presentacion;

import com.unicauca.demoobserver.dominio.entidades.Candidato;
import com.unicauca.demoobserver.dominio.entidades.Persona;
import com.unicauca.demoobserver.dominio.entidades.Voto;
import com.unicauca.demoobserver.dominio.servicios.VotosServicio;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author libardo
 */
public class GUINuevoVoto extends javax.swing.JFrame {

    private VotosServicio servicio;

    /**
     * Creates new form GUINuevoVoto
     */
    public GUINuevoVoto(VotosServicio servicio) {
        this.servicio = servicio;
        initComponents();
        llenarCandidatos();
        btnVotar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboCandidato = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtClave = new javax.swing.JFormattedTextField();
        btnVotar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de votos");
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1);

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        getContentPane().add(txtCedula);

        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2);

        lblNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblNombres);

        jLabel3.setText("Candidato");
        getContentPane().add(jLabel3);

        getContentPane().add(cboCandidato);

        jLabel4.setText("Clave secreta:");
        getContentPane().add(jLabel4);
        getContentPane().add(txtClave);

        btnVotar.setText("Votar");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVotar);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        //Validar datos

        String cedula = txtCedula.getText().trim();
        String clave = txtClave.getText().trim();
        String candidato = cboCandidato.getSelectedItem().toString();

        servicio.adicionarVoto(new Voto(servicio.getPersonaByCedula(cedula), servicio.getCandidatoByNombres(candidato), LocalDate.now()));
        JOptionPane.showMessageDialog(null, "Gracias por su voto", "Atención", JOptionPane.INFORMATION_MESSAGE);

        limpiar();
        btnVotar.setEnabled(false);
    }//GEN-LAST:event_btnVotarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        String cedula = txtCedula.getText().trim();
        if (cedula.equals("")) {
            return;
        }

        Persona per = servicio.getPersonaByCedula(cedula);
        if (per == null) {
            JOptionPane.showMessageDialog(null, "Cedula no existe en la bd de la registraduria", "Atención", JOptionPane.INFORMATION_MESSAGE);
            lblNombres.setText("");
            //limpiar();
            txtCedula.requestFocus();
            return;

        }
        
        if (per.isYaVoto()){
             JOptionPane.showMessageDialog(null, "Lo siento Usted ya votó. No lo puede volver a hacer", "Atención", JOptionPane.INFORMATION_MESSAGE);
             limpiar();
             txtCedula.requestFocus();
             return;
        }

        String nombres = per.getNombres() + " " + per.getApellidos();
        lblNombres.setText(nombres);
        btnVotar.setEnabled(true);


    }//GEN-LAST:event_txtCedulaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVotar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JFormattedTextField txtClave;
    // End of variables declaration//GEN-END:variables

    private void llenarCandidatos() {
        for (Candidato candidato : servicio.getCandidatos()) {
            cboCandidato.addItem(candidato.getNombres());
        }

    }

    private void limpiar() {
        txtCedula.setText("");
        lblNombres.setText("");
        txtClave.setText("");
        cboCandidato.setSelectedIndex(0);
    }
}
